const FALLBACK_RECIPES = {
  soup: [
    { id: 's1',  title: '豚汁',                   image: '', url: '#', materials: ['豚肉', '大根', 'にんじん', 'こんにゃく', '味噌'], indication: '20分', description: '具だくさんの豚汁。', pfc: { p: 8, f: 6, c: 10 }, role: 'soup' },
    { id: 's2',  title: '玉ねぎと豆腐の味噌汁',   image: '', url: '#', materials: ['玉ねぎ', '豆腐', '味噌', 'だし'], indication: '10分', description: 'シンプルな定番味噌汁。', pfc: { p: 5, f: 3, c: 6 }, role: 'soup' },
    { id: 's3',  title: 'ミネストローネ',           image: '', url: '#', materials: ['トマト', '玉ねぎ', 'セロリ', 'にんじん', 'ベーコン'], indication: '30分', description: '野菜たっぷりのイタリア風スープ。', pfc: { p: 5, f: 4, c: 12 }, role: 'soup' },
    { id: 's4',  title: 'わかめと長ねぎの味噌汁', image: '', url: '#', materials: ['わかめ', '長ねぎ', '味噌', 'だし'], indication: '10分', description: '磯の香りのさっぱり味噌汁。', pfc: { p: 3, f: 1, c: 4 }, role: 'soup' },
    { id: 's5',  title: 'コーンスープ',             image: '', url: '#', materials: ['コーン', '牛乳', 'バター', '玉ねぎ'], indication: '20分', description: '甘みのあるクリーミーなスープ。', pfc: { p: 4, f: 7, c: 14 }, role: 'soup' },
    { id: 's6',  title: 'けんちん汁',               image: '', url: '#', materials: ['豆腐', '大根', 'にんじん', 'ごぼう', 'こんにゃく'], indication: '25分', description: '根菜たっぷりの精進汁物。', pfc: { p: 5, f: 2, c: 11 }, role: 'soup' },
    { id: 's7',  title: 'クラムチャウダー',         image: '', url: '#', materials: ['あさり', 'じゃがいも', '玉ねぎ', '生クリーム', 'ベーコン'], indication: '25分', description: '濃厚でクリーミーな貝のスープ。', pfc: { p: 9, f: 12, c: 10 }, role: 'soup' },
    { id: 's8',  title: 'トマトスープ',             image: '', url: '#', materials: ['トマト缶', '玉ねぎ', 'コンソメ', 'オリーブオイル'], indication: '15分', description: '酸味がさっぱりのトマトスープ。', pfc: { p: 2, f: 4, c: 10 }, role: 'soup' },
    { id: 's9',  title: 'わかめスープ（韓国風）',  image: '', url: '#', materials: ['わかめ', 'ごま油', 'にんにく', '鶏ガラスープ'], indication: '10分', description: 'ヘルシーな韓国風わかめスープ。', pfc: { p: 3, f: 3, c: 2 }, role: 'soup' },
    { id: 's10', title: '卵スープ（中華）',         image: '', url: '#', materials: ['卵', '鶏ガラスープ', '長ねぎ', 'ごま油', '塩'], indication: '10分', description: 'ふわふわ卵の優しい中華スープ。', pfc: { p: 6, f: 5, c: 3 }, role: 'soup' },
    { id: 's11', title: 'ポタージュスープ',         image: '', url: '#', materials: ['じゃがいも', '玉ねぎ', '牛乳', 'バター', 'コンソメ'], indication: '25分', description: 'なめらかで濃厚なポタージュ。', pfc: { p: 4, f: 8, c: 16 }, role: 'soup' },
    { id: 's12', title: 'ポトフ',                   image: '', url: '#', materials: ['鶏肉', 'じゃがいも', 'にんじん', '玉ねぎ', 'コンソメ'], indication: '35分', description: 'じっくり煮込んだ洋風煮物スープ。', pfc: { p: 14, f: 6, c: 14 }, role: 'soup' },
    { id: 's13', title: '酸辣湯（サンラータン）',  image: '', url: '#', materials: ['豆腐', '卵', 'しいたけ', '酢', '豆板醤'], indication: '15分', description: '酸っぱ辛い本格中華スープ。', pfc: { p: 8, f: 6, c: 5 }, role: 'soup' },
    { id: 's14', title: 'オニオンスープ',           image: '', url: '#', materials: ['玉ねぎ', 'バター', 'コンソメ', 'チーズ', 'バゲット'], indication: '30分', description: '玉ねぎを飴色に炒めた濃厚スープ。', pfc: { p: 5, f: 10, c: 14 }, role: 'soup' },
    { id: 's15', title: 'なめことなすの味噌汁',    image: '', url: '#', materials: ['なめこ', 'なす', '味噌', 'だし'], indication: '10分', description: 'とろみが美味しい夏の味噌汁。', pfc: { p: 3, f: 1, c: 5 }, role: 'soup' },
  ],
  main: [
    // 和食
    { id: 'm1',  title: '鶏の唐揚げ',             image: '', url: '#', materials: ['鶏もも肉', '醤油', '生姜', 'にんにく', '片栗粉'], indication: '30分', description: '外カリ中ジューシーの定番揚げ物。', pfc: { p: 24, f: 18, c: 10 }, role: 'main' },
    { id: 'm2',  title: '鶏むね肉の塩焼き',       image: '', url: '#', materials: ['鶏むね肉', '塩', 'オリーブオイル', 'レモン'], indication: '15分', description: 'シンプルでヘルシーな高タンパク主菜。', pfc: { p: 30, f: 8, c: 1 }, role: 'main' },
    { id: 'm3',  title: '豚の生姜焼き',           image: '', url: '#', materials: ['豚肉', '生姜', '醤油', 'みりん', '玉ねぎ'], indication: '15分', description: '甘辛タレが食欲をそそる定番メニュー。', pfc: { p: 24, f: 14, c: 8 }, role: 'main' },
    { id: 'm4',  title: 'サバの味噌煮',           image: '', url: '#', materials: ['サバ', '味噌', 'みりん', '砂糖', '生姜'], indication: '25分', description: 'DHA豊富なサバの甘辛味噌煮。', pfc: { p: 24, f: 16, c: 6 }, role: 'main' },
    { id: 'm5',  title: '鮭のムニエル',           image: '', url: '#', materials: ['鮭', '小麦粉', 'バター', 'レモン', 'パセリ'], indication: '15分', description: 'バターの香りが食欲をそそる洋風魚料理。', pfc: { p: 26, f: 14, c: 4 }, role: 'main' },
    { id: 'm6',  title: '鶏もも肉の照り焼き',     image: '', url: '#', materials: ['鶏もも肉', '醤油', 'みりん', '砂糖', '酒'], indication: '20分', description: '甘辛タレが絡む人気の照り焼き。', pfc: { p: 26, f: 16, c: 8 }, role: 'main' },
    { id: 'm7',  title: '肉じゃが',               image: '', url: '#', materials: ['牛肉', 'じゃがいも', '玉ねぎ', '醤油', 'みりん'], indication: '30分', description: '日本のお袋の味。ほっこり煮物の定番。', pfc: { p: 16, f: 10, c: 20 }, role: 'main' },
    { id: 'm8',  title: '豚の角煮',               image: '', url: '#', materials: ['豚バラ肉', '醤油', 'みりん', '砂糖', '酒'], indication: '60分', description: 'とろとろに煮込んだ本格角煮。', pfc: { p: 18, f: 28, c: 8 }, role: 'main' },
    { id: 'm9',  title: '鶏そぼろ丼のたね',       image: '', url: '#', materials: ['鶏ひき肉', '醤油', 'みりん', '砂糖', '生姜'], indication: '15分', description: 'ご飯にのせるだけの万能そぼろ。', pfc: { p: 22, f: 8, c: 6 }, role: 'main' },
    { id: 'm10', title: 'アジの干物焼き',         image: '', url: '#', materials: ['アジの干物', '大根おろし', 'すだち'], indication: '10分', description: 'シンプルで美味しい定番魚料理。', pfc: { p: 20, f: 8, c: 0 }, role: 'main' },
    { id: 'm11', title: 'とんかつ',               image: '', url: '#', materials: ['豚ロース', 'パン粉', '卵', '小麦粉', '揚げ油'], indication: '30分', description: 'サクサクジューシーな揚げ物の王道。', pfc: { p: 26, f: 22, c: 14 }, role: 'main' },
    { id: 'm12', title: '鯖の塩焼き',             image: '', url: '#', materials: ['鯖', '塩', '大根おろし', 'すだち'], indication: '15分', description: '脂がのったサバのシンプル塩焼き。', pfc: { p: 22, f: 16, c: 0 }, role: 'main' },
    // 洋食
    { id: 'm13', title: 'ハンバーグ',             image: '', url: '#', materials: ['合びき肉', '玉ねぎ', '卵', 'パン粉', 'ケチャップ'], indication: '30分', description: '子どもから大人まで大人気の洋食メニュー。', pfc: { p: 22, f: 20, c: 8 }, role: 'main' },
    { id: 'm14', title: 'チキンソテー（ハーブ）', image: '', url: '#', materials: ['鶏もも肉', 'にんにく', 'ハーブ', 'オリーブオイル', 'レモン'], indication: '20分', description: '香り豊かなイタリアン風チキン。', pfc: { p: 26, f: 14, c: 1 }, role: 'main' },
    { id: 'm15', title: 'ポークソテー',           image: '', url: '#', materials: ['豚ロース', 'マスタード', 'バター', '塩', 'こしょう'], indication: '15分', description: '香ばしく焼いたポークソテー。', pfc: { p: 24, f: 16, c: 2 }, role: 'main' },
    { id: 'm16', title: 'グラタン',               image: '', url: '#', materials: ['鶏肉', 'マカロニ', '牛乳', 'バター', 'チーズ'], indication: '40分', description: 'クリーミーで濃厚な洋食の定番。', pfc: { p: 18, f: 20, c: 22 }, role: 'main' },
    { id: 'm17', title: 'ビーフシチュー',         image: '', url: '#', materials: ['牛肉', 'じゃがいも', 'にんじん', '玉ねぎ', 'デミグラスソース'], indication: '60分', description: '濃厚でコクのある洋食の煮込み。', pfc: { p: 22, f: 16, c: 20 }, role: 'main' },
    { id: 'm18', title: 'ミートソースパスタ',     image: '', url: '#', materials: ['合びき肉', 'トマト缶', '玉ねぎ', 'にんにく', 'パスタ'], indication: '30分', description: '本格的なボロネーゼ風ミートソース。', pfc: { p: 24, f: 14, c: 50 }, role: 'main' },
    { id: 'm19', title: 'カルボナーラ',           image: '', url: '#', materials: ['パスタ', 'ベーコン', '卵', 'チーズ', '黒こしょう'], indication: '20分', description: 'クリーミーな本格イタリアン。', pfc: { p: 22, f: 24, c: 48 }, role: 'main' },
    { id: 'm20', title: 'ペペロンチーノ',         image: '', url: '#', materials: ['パスタ', 'にんにく', '唐辛子', 'オリーブオイル', '塩'], indication: '15分', description: 'シンプルで奥深いイタリアンパスタ。', pfc: { p: 10, f: 14, c: 46 }, role: 'main' },
    { id: 'm21', title: 'チキンカレー',           image: '', url: '#', materials: ['鶏肉', '玉ねぎ', 'トマト', 'カレーパウダー', 'にんにく'], indication: '40分', description: 'スパイシーで香り豊かな本格カレー。', pfc: { p: 24, f: 12, c: 14 }, role: 'main' },
    { id: 'm22', title: 'サーモンのクリームソース', image: '', url: '#', materials: ['サーモン', '生クリーム', 'バター', 'ほうれん草', 'にんにく'], indication: '20分', description: '濃厚クリームソースが絡む洋風魚料理。', pfc: { p: 24, f: 22, c: 4 }, role: 'main' },
    // 中華
    { id: 'm23', title: '麻婆豆腐',               image: '', url: '#', materials: ['豆腐', 'ひき肉', '豆板醤', '甜麺醤', '長ねぎ'], indication: '20分', description: '辛さが癖になる本格中華。', pfc: { p: 18, f: 14, c: 6 }, role: 'main' },
    { id: 'm24', title: '回鍋肉',                 image: '', url: '#', materials: ['豚バラ肉', 'キャベツ', '豆板醤', '甜麺醤', 'にんにく'], indication: '20分', description: 'ご飯が進む本格中華炒め。', pfc: { p: 18, f: 16, c: 6 }, role: 'main' },
    { id: 'm25', title: '青椒肉絲',               image: '', url: '#', materials: ['牛肉', 'ピーマン', 'たけのこ', 'オイスターソース'], indication: '20分', description: '定番中華のチンジャオロース。', pfc: { p: 20, f: 12, c: 6 }, role: 'main' },
    { id: 'm26', title: 'エビのチリソース',       image: '', url: '#', materials: ['エビ', '豆板醤', 'トマトケチャップ', '長ねぎ', 'にんにく'], indication: '20分', description: 'プリプリのエビとピリ辛ソースが絶品。', pfc: { p: 20, f: 6, c: 8 }, role: 'main' },
    { id: 'm27', title: '酢豚',                   image: '', url: '#', materials: ['豚肉', 'ピーマン', '玉ねぎ', 'にんじん', '酢'], indication: '30分', description: '甘酸っぱいタレが絡む中華の定番。', pfc: { p: 18, f: 12, c: 20 }, role: 'main' },
    { id: 'm28', title: '豚キムチ炒め',           image: '', url: '#', materials: ['豚バラ肉', 'キムチ', '玉ねぎ', 'ごま油', '醤油'], indication: '15分', description: '辛旨で食欲増進の韓国風炒め物。', pfc: { p: 18, f: 16, c: 5 }, role: 'main' },
    { id: 'm29', title: 'プルコギ',               image: '', url: '#', materials: ['牛肉', '醤油', 'ごま油', 'にんにく', '梨'], indication: '20分', description: '甘辛タレが染みた韓国風焼き肉。', pfc: { p: 22, f: 14, c: 8 }, role: 'main' },
    { id: 'm30', title: '餃子',                   image: '', url: '#', materials: ['豚ひき肉', 'キャベツ', '生姜', 'にんにく', '餃子の皮'], indication: '40分', description: 'パリッと焼いた本格手作り餃子。', pfc: { p: 16, f: 14, c: 24 }, role: 'main' },
    // 豆腐・卵
    { id: 'm31', title: '豆腐ステーキ',           image: '', url: '#', materials: ['木綿豆腐', '醤油', 'みりん', 'ごま油', '生姜'], indication: '15分', description: 'ヘルシーで満足感のある豆腐メニュー。', pfc: { p: 12, f: 8, c: 4 }, role: 'main' },
    { id: 'm32', title: 'オムレツ',               image: '', url: '#', materials: ['卵', '牛乳', 'バター', '塩', 'こしょう'], indication: '10分', description: 'ふわとろの洋風卵料理。', pfc: { p: 14, f: 16, c: 2 }, role: 'main' },
    { id: 'm33', title: '親子煮',                 image: '', url: '#', materials: ['鶏もも肉', '玉ねぎ', '卵', '醤油', 'みりん'], indication: '20分', description: '出汁が染みた甘辛の親子煮。', pfc: { p: 25, f: 14, c: 8 }, role: 'main' },
    { id: 'm34', title: '卵とトマトの炒め物',     image: '', url: '#', materials: ['卵', 'トマト', '塩', 'ごま油', '長ねぎ'], indication: '10分', description: 'シンプルな中華風卵炒め。', pfc: { p: 10, f: 10, c: 6 }, role: 'main' },
    { id: 'm35', title: '鶏ハム',                 image: '', url: '#', materials: ['鶏むね肉', '塩', '砂糖', 'ハーブ', 'ラップ'], indication: '30分', description: 'しっとり柔らかい自家製鶏ハム。', pfc: { p: 28, f: 4, c: 0 }, role: 'main' },
    { id: 'm36', title: 'ぶりの照り焼き',         image: '', url: '#', materials: ['ぶり', '醤油', 'みりん', '砂糖', '酒'], indication: '20分', description: '脂がのったぶりの甘辛照り焼き。', pfc: { p: 24, f: 14, c: 6 }, role: 'main' },
    { id: 'm37', title: 'タコライスのたね',       image: '', url: '#', materials: ['牛ひき肉', 'トマト', 'チーズ', 'レタス', 'タコスシーズニング'], indication: '20分', description: '沖縄発のエスニック風ごはんのお供。', pfc: { p: 20, f: 16, c: 6 }, role: 'main' },
    { id: 'm38', title: 'チキン南蛮',             image: '', url: '#', materials: ['鶏むね肉', '卵', '小麦粉', '酢', '砂糖'], indication: '30分', description: '甘酢ダレとタルタルの宮崎名物。', pfc: { p: 24, f: 20, c: 16 }, role: 'main' },
    { id: 'm39', title: 'ガパオライスのたね',     image: '', url: '#', materials: ['鶏ひき肉', 'バジル', 'ナンプラー', '唐辛子', 'にんにく'], indication: '15分', description: 'タイ風の香り高い炒め物。', pfc: { p: 20, f: 10, c: 4 }, role: 'main' },
    { id: 'm40', title: 'サバ缶と大根の煮物',     image: '', url: '#', materials: ['サバ缶', '大根', '醤油', 'みりん', '生姜'], indication: '20分', description: '缶詰で手軽に作れる栄養満点煮物。', pfc: { p: 20, f: 10, c: 8 }, role: 'main' },
  ],
  side: [
    { id: 'd1',  title: 'ほうれん草のおひたし',   image: '', url: '#', materials: ['ほうれん草', '醤油', 'だし', 'かつお節'], indication: '10分', description: 'シンプルで栄養満点の定番副菜。', pfc: { p: 3, f: 1, c: 2 }, role: 'side' },
    { id: 'd2',  title: 'きんぴらごぼう',         image: '', url: '#', materials: ['ごぼう', 'にんじん', '醤油', 'みりん', 'ごま油'], indication: '15分', description: '食物繊維たっぷりの和風副菜。', pfc: { p: 2, f: 3, c: 14 }, role: 'side' },
    { id: 'd3',  title: 'ブロッコリーのサラダ',   image: '', url: '#', materials: ['ブロッコリー', 'マヨネーズ', 'コーン', '塩'], indication: '10分', description: '彩りよくビタミン豊富なサラダ。', pfc: { p: 4, f: 6, c: 5 }, role: 'side' },
    { id: 'd4',  title: 'ひじきの煮物',           image: '', url: '#', materials: ['ひじき', '油揚げ', 'にんじん', '醤油', 'みりん'], indication: '20分', description: 'ミネラル豊富なひじきの定番副菜。', pfc: { p: 3, f: 4, c: 8 }, role: 'side' },
    { id: 'd5',  title: '大根サラダ',             image: '', url: '#', materials: ['大根', 'にんじん', 'ポン酢', 'ごま油', 'かつお節'], indication: '10分', description: 'さっぱりと食べられる和風サラダ。', pfc: { p: 1, f: 2, c: 5 }, role: 'side' },
    { id: 'd6',  title: '卵焼き',                 image: '', url: '#', materials: ['卵', '醤油', 'みりん', '砂糖', 'だし'], indication: '10分', description: '甘めのだし巻き風卵焼き。', pfc: { p: 8, f: 7, c: 3 }, role: 'side' },
    { id: 'd7',  title: '小松菜の炒め物',         image: '', url: '#', materials: ['小松菜', 'にんにく', '醤油', 'ごま油', 'ちりめんじゃこ'], indication: '10分', description: 'カルシウム豊富でシャキシャキ食感。', pfc: { p: 5, f: 4, c: 3 }, role: 'side' },
    { id: 'd8',  title: 'かぼちゃの煮物',         image: '', url: '#', materials: ['かぼちゃ', '醤油', 'みりん', '砂糖', 'だし'], indication: '20分', description: 'ほっくり甘いかぼちゃの定番煮物。', pfc: { p: 2, f: 1, c: 18 }, role: 'side' },
    { id: 'd9',  title: 'ポテトサラダ',           image: '', url: '#', materials: ['じゃがいも', 'ハム', '玉ねぎ', 'マヨネーズ', 'きゅうり'], indication: '25分', description: '定番のポテトサラダ。', pfc: { p: 4, f: 10, c: 16 }, role: 'side' },
    { id: 'd10', title: '切り干し大根',           image: '', url: '#', materials: ['切り干し大根', 'にんじん', '油揚げ', '醤油', 'みりん'], indication: '20分', description: '食物繊維・カルシウム豊富な副菜。', pfc: { p: 3, f: 2, c: 12 }, role: 'side' },
    { id: 'd11', title: 'コールスロー',           image: '', url: '#', materials: ['キャベツ', 'にんじん', 'マヨネーズ', '酢', '砂糖'], indication: '10分', description: '甘酸っぱくてさっぱりの洋風副菜。', pfc: { p: 1, f: 8, c: 6 }, role: 'side' },
    { id: 'd12', title: 'ラタトゥイユ',           image: '', url: '#', materials: ['なす', 'ズッキーニ', 'トマト', '玉ねぎ', 'オリーブオイル'], indication: '30分', description: '南フランスの野菜煮込み。', pfc: { p: 2, f: 5, c: 10 }, role: 'side' },
    { id: 'd13', title: 'もやしのナムル',         image: '', url: '#', materials: ['もやし', 'ごま油', '塩', 'にんにく', '白ごま'], indication: '10分', description: 'シャキシャキ食感の韓国風副菜。', pfc: { p: 2, f: 3, c: 3 }, role: 'side' },
    { id: 'd14', title: 'アボカドサラダ',         image: '', url: '#', materials: ['アボカド', 'トマト', 'レモン', 'オリーブオイル', '塩'], indication: '5分', description: 'クリーミーで栄養満点のサラダ。', pfc: { p: 2, f: 14, c: 5 }, role: 'side' },
    { id: 'd15', title: 'きゅうりの浅漬け',       image: '', url: '#', materials: ['きゅうり', '塩', '生姜', '昆布', '酢'], indication: '30分', description: 'さっぱり爽やかな浅漬け。', pfc: { p: 1, f: 0, c: 3 }, role: 'side' },
    { id: 'd16', title: 'ほうれん草のソテー',     image: '', url: '#', materials: ['ほうれん草', 'バター', 'にんにく', '塩', 'こしょう'], indication: '10分', description: 'バター風味の洋風ソテー。', pfc: { p: 3, f: 4, c: 2 }, role: 'side' },
    { id: 'd17', title: '春雨サラダ',             image: '', url: '#', materials: ['春雨', 'きゅうり', 'ハム', '酢', 'ごま油'], indication: '15分', description: 'さっぱり中華風春雨サラダ。', pfc: { p: 4, f: 4, c: 18 }, role: 'side' },
    { id: 'd18', title: 'ブロッコリーとベーコンの炒め物', image: '', url: '#', materials: ['ブロッコリー', 'ベーコン', 'にんにく', 'オリーブオイル', '塩'], indication: '10分', description: '食べ応えのある洋風炒め物。', pfc: { p: 8, f: 8, c: 4 }, role: 'side' },
    { id: 'd19', title: 'かぼちゃのサラダ',       image: '', url: '#', materials: ['かぼちゃ', 'マヨネーズ', 'レーズン', '塩', 'こしょう'], indication: '20分', description: '甘みのあるかぼちゃのマヨサラダ。', pfc: { p: 2, f: 8, c: 16 }, role: 'side' },
    { id: 'd20', title: 'なすの揚げびたし',       image: '', url: '#', materials: ['なす', 'だし', '醤油', 'みりん', '生姜'], indication: '20分', description: 'とろとろのなすに出汁が染みた副菜。', pfc: { p: 2, f: 6, c: 6 }, role: 'side' },
  ],
};
